[package]
name = "rs_kafka_consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
kafka = "0.10.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
